const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('maskot', {
  onUsage: (cb) => ipcRenderer.on('usage', (_e, data) => cb(data)),
  onAlert: (cb) => ipcRenderer.on('usage-alert', (_e, data) => cb(data)),
  onSessionReset: (cb) => ipcRenderer.on('session-reset', (_e, data) => cb(data)),
  onPlayPerf: (cb) => ipcRenderer.on('play-perf', (_e, name) => cb(name)),
  onConfig: (cb) => ipcRenderer.on('config', (_e, config) => cb(config)),
  onFlip: (cb) => ipcRenderer.on('flip', (_e, flipped) => cb(flipped)),
  onEditName: (cb) => ipcRenderer.on('edit-name', () => cb()),
  refresh: () => ipcRenderer.invoke('refresh-usage'),
  ask: (question, files) => ipcRenderer.invoke('ask-claude', question, files),
  pathForFile: (file) => webUtils.getPathForFile(file),
  onAskDelta: (cb) => ipcRenderer.on('ask-delta', (_e, text) => cb(text)),
  onAskReset: (cb) => ipcRenderer.on('ask-reset', () => cb()),
  onFocusAsk: (cb) => ipcRenderer.on('focus-ask', () => cb()),
  onMusic: (cb) => ipcRenderer.on('music', (_e, state) => cb(state)),
  musicToggle: () => ipcRenderer.send('music-toggle'),
  musicNext: () => ipcRenderer.send('music-next'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  setName: (name) => ipcRenderer.invoke('set-name', name),
  folderMenu: () => ipcRenderer.send('folder-menu'),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  setIgnore: (ignore) => ipcRenderer.send('set-ignore', ignore),
  contextMenu: () => ipcRenderer.send('context-menu'),
});
